package com.byron.combustible;

import org.apache.poi.xwpf.usermodel.*;
import javax.swing.*; import javax.swing.table.DefaultTableModel; import java.awt.*; import java.io.FileOutputStream; import java.time.*; import java.time.format.DateTimeFormatter; import java.util.*;

public class ControlCombustibleGUI extends JFrame {
 private final JTextField fecha=new JTextField(LocalDate.now().toString()), persona=new JTextField(), recorrido=new JTextField(), kms=new JTextField(), precio=new JTextField();
 private final JTextArea motivo=new JTextArea(3,20); private final JComboBox<String> tipoPersona=new JComboBox<>(new String[]{"Empleado municipal","Particular"}); private final JComboBox<String> combustible=new JComboBox<>(new String[]{"Gasolina Regular","Gasolina Superior","Diésel"});
 private final DefaultTableModel modelo=new DefaultTableModel(new String[]{"Fecha","Persona","Tipo","Recorrido","Combustible","Kms","Precio/L","Motivo","Costo"},0); private final JTable tabla=new JTable(modelo);
 public ControlCombustibleGUI(){setTitle("Control de Combustible");setDefaultCloseOperation(EXIT_ON_CLOSE);setSize(1200,700);setLocationRelativeTo(null); construir();}
 private void construir(){
  JPanel root=new JPanel(new BorderLayout(12,12));root.setBorder(BorderFactory.createEmptyBorder(15,15,15,15));root.setBackground(new Color(245,247,250));
  JLabel t=new JLabel("CONTROL DE COMBUSTIBLE",SwingConstants.CENTER);t.setFont(new Font("SansSerif",Font.BOLD,26));root.add(t,BorderLayout.NORTH);
  JPanel form=new JPanel(new GridLayout(5,4,8,8));form.setBorder(BorderFactory.createTitledBorder("Registro diario"));
  add(form,"Fecha (AAAA-MM-DD)",fecha);add(form,"Nombre",persona);add(form,"Tipo de persona",tipoPersona);add(form,"Recorrido",recorrido);add(form,"Tipo de combustible",combustible);add(form,"Kilómetros a recorrer",kms);add(form,"Precio combustible/L",precio);add(form,"Motivo del viaje",new JScrollPane(motivo));
  JButton agregar=new JButton("Agregar / Guardar");JButton editar=new JButton("Modificar seleccionado");JButton borrar=new JButton("Borrar seleccionado");JButton reporte=new JButton("Reporte semanal Word");
  form.add(agregar);form.add(editar);form.add(borrar);form.add(reporte);root.add(form,BorderLayout.NORTH);
  root.add(new JScrollPane(tabla),BorderLayout.CENTER);
  JPanel sur=new JPanel(new FlowLayout(FlowLayout.LEFT));JLabel resumen=new JLabel("Total: Q0.00 | Hoy: Q0.00 | Semana: Q0.00");sur.add(resumen);root.add(sur,BorderLayout.SOUTH);
  Runnable actualizar=()->resumen.setText(String.format("Total: Q%.2f | Hoy: Q%.2f | Semana: Q%.2f",total(),totalDia(LocalDate.now()),totalSemana()));
  agregar.addActionListener(e->{try{LocalDate f=LocalDate.parse(fecha.getText());double k=Double.parseDouble(kms.getText()),p=Double.parseDouble(precio.getText());if(persona.getText().isBlank()||recorrido.getText().isBlank()||k<0||p<0)throw new Exception();modelo.addRow(new Object[]{f,persona.getText(),tipoPersona.getSelectedItem(),recorrido.getText(),combustible.getSelectedItem(),k,p,motivo.getText(),k*p});actualizar.run();limpiar();}catch(Exception ex){JOptionPane.showMessageDialog(this,"Revise fecha, kilómetros, precio y campos obligatorios.");}});
  editar.addActionListener(e->{int r=tabla.getSelectedRow();if(r<0){JOptionPane.showMessageDialog(this,"Seleccione un registro.");return;}try{LocalDate f=LocalDate.parse(fecha.getText());double k=Double.parseDouble(kms.getText()),p=Double.parseDouble(precio.getText());modelo.setValueAt(f,r,0);modelo.setValueAt(persona.getText(),r,1);modelo.setValueAt(tipoPersona.getSelectedItem(),r,2);modelo.setValueAt(recorrido.getText(),r,3);modelo.setValueAt(combustible.getSelectedItem(),r,4);modelo.setValueAt(k,r,5);modelo.setValueAt(p,r,6);modelo.setValueAt(motivo.getText(),r,7);modelo.setValueAt(k*p,r,8);actualizar.run();}catch(Exception ex){JOptionPane.showMessageDialog(this,"Datos inválidos.");}});
  borrar.addActionListener(e->{int r=tabla.getSelectedRow();if(r>=0){modelo.removeRow(r);actualizar.run();}});
  reporte.addActionListener(e->crearWord()); tabla.getSelectionModel().addListSelectionListener(e->{if(!e.getValueIsAdjusting()&&tabla.getSelectedRow()>=0)cargarSeleccion();}); setContentPane(root);
 }
 private void add(JPanel p,String l,Component c){p.add(new JLabel(l));p.add(c);}
 private void cargarSeleccion(){int r=tabla.getSelectedRow();fecha.setText(modelo.getValueAt(r,0).toString());persona.setText(modelo.getValueAt(r,1).toString());tipoPersona.setSelectedItem(modelo.getValueAt(r,2));recorrido.setText(modelo.getValueAt(r,3).toString());combustible.setSelectedItem(modelo.getValueAt(r,4));kms.setText(modelo.getValueAt(r,5).toString());precio.setText(modelo.getValueAt(r,6).toString());motivo.setText(modelo.getValueAt(r,7).toString());}
 private double total(){double x=0;for(int i=0;i<modelo.getRowCount();i++)x+=Double.parseDouble(modelo.getValueAt(i,8).toString());return x;}
 private double totalDia(LocalDate d){double x=0;for(int i=0;i<modelo.getRowCount();i++)if(LocalDate.parse(modelo.getValueAt(i,0).toString()).equals(d))x+=Double.parseDouble(modelo.getValueAt(i,8).toString());return x;}
 private double totalSemana(){LocalDate h=LocalDate.now(),inicio=h.minusDays(h.getDayOfWeek().getValue()-1);double x=0;for(int i=0;i<modelo.getRowCount();i++){LocalDate d=LocalDate.parse(modelo.getValueAt(i,0).toString());if(!d.isBefore(inicio)&&!d.isAfter(h))x+=Double.parseDouble(modelo.getValueAt(i,8).toString());}return x;}
 private void limpiar(){persona.setText("");recorrido.setText("");kms.setText("");motivo.setText("");}
 private void crearWord(){JFileChooser fc=new JFileChooser();fc.setSelectedFile(new java.io.File("Reporte_Semanal_Combustible.docx"));if(fc.showSaveDialog(this)!=JFileChooser.APPROVE_OPTION)return;try(XWPFDocument doc=new XWPFDocument()){XWPFParagraph p=doc.createParagraph();p.setAlignment(ParagraphAlignment.CENTER);XWPFRun r=p.createRun();r.setBold(true);r.setFontSize(18);r.setText("REPORTE SEMANAL DE COMBUSTIBLE");doc.createParagraph().createRun().setText("Generado: "+LocalDate.now().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));XWPFTable tb=doc.createTable(modelo.getRowCount()+1,9);String[] hs={"Fecha","Persona","Tipo","Recorrido","Combustible","Kms","Precio/L","Motivo","Costo"};for(int j=0;j<9;j++)tb.getRow(0).getCell(j).setText(hs[j]);for(int i=0;i<modelo.getRowCount();i++)for(int j=0;j<9;j++)tb.getRow(i+1).getCell(j).setText(modelo.getValueAt(i,j).toString());doc.createParagraph().createRun().setText(String.format("TOTAL DE COMBUSTIBLE GASTADO EN LA SEMANA: Q%.2f",totalSemana()));doc.createParagraph().createRun().setText(String.format("TOTAL GASTADO HOY: Q%.2f",totalDia(LocalDate.now())));try(FileOutputStream out=new FileOutputStream(fc.getSelectedFile())){doc.write(out);}JOptionPane.showMessageDialog(this,"Reporte Word creado correctamente.");}catch(Exception ex){JOptionPane.showMessageDialog(this,"No se pudo crear el reporte: "+ex.getMessage());}}
 public static void main(String[]a){SwingUtilities.invokeLater(()->new ControlCombustibleGUI().setVisible(true));}
}
